# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  custom:
    test-branch:
      - step:
          script:
            - npm install
            - npm install -g firebase-tools
            - npm run build
            - firebase deploy --only hosting:test-pokerload
            - echo "Deployed to test enviroment -> test-pokerload.web.app"
  branches:
    master:
      - step:
          deployment: production
          caches:
            - node
          script:
            - npm install
            - npm install -g firebase-tools
            - npm run build
            - firebase deploy --only hosting:production-pokerload
            - echo "Deployed to production enviroment -> https://pokerload.com/"
    staging:
      - step:
          deployment: staging
          caches:
            - node
          script:
            - npm install
            - npm install -g firebase-tools
            - npm run build
            - firebase deploy --only hosting:staging-pokerload
            - echo "Deployed to staging enviroment -> https://staging.pokerload.com"
